services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    container_name: db_students

    environment:
      POSTGRES_USER: eric
      POSTGRES_PASSWORD: azul20264552
      POSTGRES_DB: students_db
  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    container_name: redis_queue

volumes:
  postgres_data: