services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    container_name: db_students

    environment:
      POSTGRES_USER: eric
      POSTGRES_PASSWORD: azul20264552
      POSTGRES_DB: students_db
  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: